# Generated by Django 4.2.5 on 2023-09-07 14:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postattachment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
